### ISSUE TITLE
在sae上部署无法找到你的类，改了名字之后，无法加载样式

### ISSUE THREAD

**Issue by k243381051** [postor/yii2-for-sae#1]
期待你的回复243381051@qq.com

**Comment by postor** [comment]
如果不是用compoer就需要自己配置好引用
安装好的目录在vendor/postor/sae/SaeAssetManager.php
compoer会自动添加代码到vendor/yiisoft/extensions.php
代码段例子：
'postor/sae' => 
  array (
    'name' => 'postor/sae',
    'version' => '0.0.1',
    'alias' => 
    array (
      '@postor/sae' => $vendorDir . '/postor/yii2-for-sae',
    ),
  ),

**Comment by postor** [comment]
0.0.5版本已经修复
