### ISSUE TITLE
wrong for that : register assets in view

### ISSUE THREAD

**Issue by clh021** [postor/yii2-for-sae#3]
刚刚我试图移植一个应用到SAE中，如下代码所示，在模板中发布的资源，会提示错误
`$this->registerJsFile($js_script, ['depends' => \yii\web\JqueryAsset::className(),'position'=>\yii\web\View::POS_HEAD]);`
错误信息如下：
`Exception (Invalid Configuration) 'yii\base\InvalidConfigException' with message 'Invalid asset bundle configuration: ......`

**Comment by postor** [comment]
大概是单个js的注册没有实现，你试试以bondle的形式注册js吧

**Comment by clh021** [comment]
嗯嗯，我主要是向你反馈，我已经把资源都通过bondle形式注册了。
我这里看到的结果是，文件形式的资源注册都有问题，如：
`registerJsFile,registerCssFile`
非文件形式的就没有问题，如：
`registerJs,registerCss`

**Comment by postor** [comment]
我就不去支持单文件的注册了，这个库本身就很小众了，需要的可以fork源码去修改
