### ISSUE TITLE
关于assets的问题

### ISSUE THREAD

**Issue by weiforrest** [postor/yii2-for-sae#4]
按照使用方法,将yii2-app-basic修改了放到sae上去,但是主页的结果是空,查看日志,显示HTTP的状态是500.
我想是不是因为我 没有使用数据库.但是开启了DbTarget.或者是Stroage 的配置出问题了,我只新建了assets域.没有上传任何文件.谢谢

**Comment by postor** [comment]
至少需要一个存数据的地方，sae不让文件操作，你不开数据库也需要别的东西放它的log、缓存啥的
