### ISSUE TITLE
yii2的目录结构里没有config/web.php这个文件呢？

### ISSUE THREAD

**Issue by liuyongfei1** [postor/yii2-for-sae#5]
yii2的目录结构里没有config/web.php这个文件呢？
是要在哪个目录下面新建这个config/web.php吗？

**Comment by postor** [comment]
http://www.yiiframework.com/doc-2.0/guide-start-workflow.html#application-structure

**Comment by liuyongfei1** [comment]
原来这个是拿 basic版的，我使用的是advanced版的。建议在README.md里说明一下。
